### PR TITLE
Add Auth0 authentication example

### PR DESCRIPTION
**Pull request by gguillemas**
This example shows how Auth0 can be used as an authentication provider by web applications that rely on SurrealDB as the only backend. The application will authenticate the user with Auth0 and use the access token issued to create or update their user in the SurrealDB backend. It will also demonstrate how the authenticated user is only authorized to query their own user record from SurrealDB.

**Important**: This example is intended to be used alongside the Auth0 Integration Guide, yet to be published.

### CODE REVIEW

**Comment by gguillemas** [comment]
The links to the Auth0 Integration Guide will be updated once the guide is released. Since the guide should contain links to the example application, I would suggest merging it prior to releasing the guide.

**Comment by sgirones** [comment]
LGTM. @kearfy could you review it too?

**Review by kearfy — APPROVED** [review]
Looks good to me! Is there a PR for the guide already too?

**Comment by gguillemas** [comment]
> Looks good to me! Is there a PR for the guide already too?

Thank you for the review! The guide is currently under review, I believe.

**Pull request merged**
